#!/bin/bash
. ${OPENSHIFT_DATA_DIR}diy_env.sh
cd ${OPENSHIFT_REPO_DIR}

if [ ! -e ${OPENSHIFT_REPO_DIR}node_modules ]; then
	mkdir -p ${OPENSHIFT_DATA_DIR}node_modules
	ln -s ${OPENSHIFT_DATA_DIR}node_modules
fi
npm install

which coffee &>/dev/null || npm install coffee-script -g
which supervisor &>/dev/null || npm install supervisor -g

if [ -e ${OPENSHIFT_DATA_DIR}keys.js ]; then
	ln -s ${OPENSHIFT_DATA_DIR}keys.js
fi