#!/bin/bash
cd ${OPENSHIFT_REPO_DIR}
NODE_VERSION='v0.10.8'
NODE_REMOVE_OLD='true'
CARTRIDGE_NAME='diy-0.1'

if [ -z $OPENSHIFT_RUN_DIR ]; then
  export OPENSHIFT_RUN_DIR=${OPENSHIFT_HOMEDIR}${CARTRIDGE_NAME}/run/
fi

if [ ! -e ${OPENSHIFT_DATA_DIR}node-${NODE_VERSION}/bin/node ]; then

  if [ $NODE_REMOVE_OLD == "true" ]; then
    echo "rm -rf ${OPENSHIFT_DATA_DIR}node-*"
    rm -rf ${OPENSHIFT_DATA_DIR}node-*
  fi
  cd ${OPENSHIFT_TMP_DIR}

  if [ "`uname -i`" == "x86_64" ]; then
    TYPE="x64"
  else
    TYPE="x86"
  fi
  BINARY="http://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION-linux-$TYPE.tar.gz"

  if [ "`curl -Is $BINARY | grep '200 OK'`" != '' ]; then
    curl -L -o node-${NODE_VERSION}-linux-${TYPE}.tar.gz $BINARY
    tar -xvzf node-${NODE_VERSION}-linux-${TYPE}.tar.gz
    mv node-${NODE_VERSION}-linux-${TYPE} ${OPENSHIFT_DATA_DIR}node-${NODE_VERSION}
    rm -f node-${NODE_VERSION}-linux-${TYPE}.tar.gz
  else

    tarball=''
    if [ "`curl -Is "http://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION.tar.gz" | grep '200 OK'`" != '' ]; then
      tarball="http://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION.tar.gz"
    elif [ "`curl -Is "http://nodejs.org/dist/node-$NODE_VERSION.tar.gz" | grep '200 OK'`" != '' ]; then
      tarball="http://nodejs.org/dist/node-$NODE_VERSION.tar.gz"
    fi
    # Check is tarball already download and extracted
    if [ ! -d node-${NODE_VERSION} ]; then
      curl -L -o node-${NODE_VERSION}.tar.gz $tarball
      tar -xvzf node-${NODE_VERSION}.tar.gz
    fi
    cd node-${NODE_VERSION}
    echo "Start compiling Node ${NODE_VERSION} on Openshift (it'll take a while)"
    ./configure --prefix="${OPENSHIFT_DATA_DIR}node-${NODE_VERSION}" && make && make install

    cd ${OPENSHIFT_TMP_DIR}
    rm -f node-${NODE_VERSION}.tar.gz
    rm -rf node-${NODE_VERSION}/
  fi
fi

cat <<EOF > ${OPENSHIFT_DATA_DIR}diy_env.sh
export NODE_VERSION=${NODE_VERSION}
export TMPDIR=\${OPENSHIFT_TMP_DIR}
if [ -z \$NODE_DEFINED ]; then
  export NODE_DEFINED=1
  export PATH="\${OPENSHIFT_DATA_DIR}node-\${NODE_VERSION}/bin:\$PATH"
  export npm_config_cache=\${OPENSHIFT_DATA_DIR}node-\${NODE_VERSION}/.npm
  export npm_config_userconfig=\${OPENSHIFT_DATA_DIR}node-\${NODE_VERSION}/.npmrc
  export npm_config_userignorefile=\${OPENSHIFT_DATA_DIR}node-\${NODE_VERSION}/.npmignore
  export npm_config_tmp=\${OPENSHIFT_TMP_DIR}
  export NODE_ENV=production
fi
if [ -z \$OPENSHIFT_RUN_DIR ]; then
  export OPENSHIFT_RUN_DIR=\${OPENSHIFT_HOMEDIR}${CARTRIDGE_NAME}/run/
fi
EOF
chmod +x ${OPENSHIFT_DATA_DIR}diy_env.sh