#!/bin/bash
. ${OPENSHIFT_DATA_DIR}diy_env.sh
cd ${OPENSHIFT_REPO_DIR}

APP_FILE=`node -e 'var package=require("./package.json");console.log(package.main);'`

LOG_FILE=${OPENSHIFT_DIY_LOG_DIR}server.log
if [ -s $LOG_FILE ]; then

  MODIFY=`stat -c "%Y" $LOG_FILE`

  STAMP=`date -d @$MODIFY "+%Y%m%d-%H%M%S"`
  mv -f $LOG_FILE ${LOG_FILE}.${STAMP}
fi
echo "Node Version:"
node -e 'console.log(process.versions);'

echo "nohup supervisor $APP_FILE >$LOG_FILE 2>&1 &"
nohup supervisor -w . $APP_FILE >$LOG_FILE 2>&1 &